[package]
name = "differential-dataflow-demo"
version = "0.1.0"
authors = ["Jamie Brandon <jamie@scattered-thoughts.net>"]
edition = "2018"

[dependencies]
timely = "0.12.0"
differential-dataflow = "0.12.0"
chrono = "0.4.19"
serde_json = "1.0.59"
ordered-float = "2.1.1"
abomonation_derive = "0.5.0"